version: '3.3'

services:
  db:
    container_name: message-container
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: message_task_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: 11111111
  app:
    image: message-task
    build: ./
    container_name: message-task
    ports:
      - "7070:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/message_task_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=11111111
    depends_on:
      - db
volumes:
  db:
    driver: local