
CREATE TABLE IF NOT EXISTS users(
                                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    username VARCHAR(100),
    password VARCHAR(100)
    );
CREATE TABLE IF NOT EXISTS message(
                                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       message VARCHAR(1000),
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES users(id)
    );

INSERT INTO users VALUES(1, 'test', 'testpass');
INSERT INTO users VALUES(2, 'test1', 'testpass');